# Generated by Django 4.1.5 on 2023-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('cc', models.IntegerField(primary_key=True, serialize=False)),
                ('projeto_name', models.CharField(max_length=200)),
            ],
        ),
    ]
