# Generated by Django 4.1.5 on 2023-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='cc',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
