# Generated by Django 4.1.5 on 2023-01-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0002_alter_projeto_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painel_name', models.CharField(max_length=200)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projeto.projeto')),
            ],
        ),
    ]
