# Generated by Django 4.1.5 on 2023-01-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0003_painel'),
        ('QrCode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='painel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Projeto.painel'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='projeto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
