# Generated by Django 4.1.5 on 2023-01-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0003_painel'),
        ('QrCode', '0002_qrcode_painel_qrcode_projeto_alter_qrcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='painel',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='Projeto.painel'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='projeto',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='Projeto.projeto'),
        ),
    ]
