# Generated by Django 4.1.5 on 2023-01-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrCode', '0003_alter_qrcode_painel_alter_qrcode_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='painel',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='projeto',
        ),
    ]
